### ISSUE TITLE
Lint

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#1]
Fix eslint process. Currently broken because of babel/es6 syntax in app. Also support different settings for dev mode.

**Comment by vbulant** [comment]
Already on it.

**Comment by janpanschab** [comment]
Problem is to merge options once for dev mode and once for production mode.

**Comment by janpanschab** [comment]
Aha, so merging of options is like: base options are in .eslintrc and options from gulp task (api) are merged with .eslintrc?

**Comment by vbulant** [comment]
Yep, exactly.
Separation between dev/prod is fixed and tested, I consider this done.
