### ISSUE TITLE
Styles: Wrong "on" method

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#107]
I have stumbled upon an interesting [comment](https://github.com/postcss/postcss/issues/766#issuecomment-195207035) about handling `sass()` error.

**Comment by janpanschab** [comment]
Is it a problem/bug in current version?

**Comment by kettanaito** [comment]
@janpanschab we have the same code as the person in the issue above. It does not produce errors for now, but, eventually, this is improper usage of the method:
```js
// current version
.pipe(sass().on('error', /*...*/)

// proper usage
.pipe(sass()).on('error', /*...*/)
```
