### ISSUE TITLE
Layout: main class

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#108]
The current usage:
```html
<main role="main" class="container">
```

## Remove "container" class
I would not recommend using bootstrap's `container` class on the root node of page content. Suggesting to nest it inside the `<main>` tag:
```html
<main role="main">
    <div class="container">
    </div>
</main>
```

## Remove `role="main"`
There is a [great tool for HTML5 proper markup validation](http://validator.w3.org/nu). When uploaded our `index.html` we get a following error:
```
Warning: Element `main` does not need a `role` attribute.
```
I think this is because there can be only one `<main>` tag in the whole document. ARIA specification attributes were provided before roles were natively supported by HTML5.

Usage of HTML5 markup should be supported, since it is not even a new feature as for 2016.

**Comment by kettanaito** [comment]
It should be also discussed whether we really need to nest `div class="container">` inside `<main>`.

What about instances when nested content has fluid container? Maybe it is better to define container in each `block` macro extension?

**Comment by janpanschab** [comment]
This depends on project. IMHO this is quite easy task and we don’t need to show best practice here.

**Comment by kettanaito** [comment]
@janpanschab then I will create a pull request with the changes I currently have.
