### ISSUE TITLE
ESLint: Class method uses this

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#115]
A rule `class-methods-use-this` is buggy regarding React Components (as noticed by @ronaldruzicka ), and also [here](https://github.com/eslint/eslint/issues/7085).

Possible solutions:
1. Ignore the rule completely (what is a benefit of it?)
2. Use `exceptMethods` option for this rule, as mentioned [here](https://github.com/eslint/eslint/issues/7085#issuecomment-250465391), to make it ignore React methods until they are properly parsed.

**Comment by vbulant** [comment]
Ad 1. it tells you that class method is pointless when you don’t need `this` and that you can use plain function instead.
Ad 2. that would help in case of `componentDidMount` etc. but once you need custom `renderSomething()` methods, it’s useless.

I like the hint that you shouldn’t overuse class methods when not needed. But writing render helpers outside of React classes seems weird to me as well.

So I don’t really know at the moment.

cc @janpanschab

**Comment by vbulant** [comment]
Support for `exceptMethod` [has been added](https://github.com/eslint/eslint/blob/master/docs/rules/class-methods-use-this.md)

Let’s try it and close the issue.
