### ISSUE TITLE
Move to project based .eslintrc from eslint-config-actum

### ISSUE THREAD

**Issue by vbulant** [actum/gulp-dev-stack#117]
Although it’s a noble idea to have a reusable eslint config package, it’s not that handy for maintenance.

We already discussed it with @janpanschab and suggest to move to the project based config which extends airbnb config.

**Comment by kettanaito** [comment]
@vbulant what were the blocking moments which made it non-maintainable?

**Comment by vbulant** [comment]
If you want to tweak the rules you have to modify the eslint-config-actum. Then if it’s fine, you have to publish it… Then it can break another project which uses it. So we could use semver and refer to exact versions.

Still, we think it’s too much of an overhead and having local eslint is more straightforward.

**Comment by kettanaito** [comment]
I thought of workflow to be somehow like:
1. Extend `actum-eslint-config` with the minimal/recommended setup of rules
2. When some tweak is needed, just add it in the project's .eslint (the same place where it extends our rules), not the `actum-eslint-config` repo. Manually set rules will always overwrite extensions.

But if you find it hard to maintain that's okay, then we should use it separately.

**Comment by ronaldruzicka** [comment]
Example of extending:

```js
const eslintConfig = require('eslint-config-actum').getConfig({ environment });

const lint = (globs) => {
    const options = {
        configFile: eslintConfig,
        globals: [
            "jQuery",
            "$"
        ]
    };
```

**Comment by vbulant** [comment]
I think the extension shown by Ronald is fine. Let’s stick with that. @kettanaito thanks for your clarification.
