### ISSUE TITLE
Swig watch reload before task finished

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#12]
Sometimes when I save swig template the page is reloaded, but nothing happen. After second safe the changes are reflected. It looks like the reload event is triggered before the swig compilation is finished.

**Comment by vbulant** [comment]
I was not able to reproduce this.

However, there is another approach to reload manually that could help: `.on('end', browserSync.reload)` instead of just injecting changed HTML using `.pipe`.

**Comment by vbulant** [comment]
After closing https://github.com/actum/gulp-dev-stack/issues/17 it seems that reload after nunjucks compilation works fine.

**Comment by janpanschab** [comment]
Closing. Nunjucks are OK.
