### ISSUE TITLE
Usage of Gulp variables in task js.js

### ISSUE THREAD

**Issue by honzachalupa** [actum/gulp-dev-stack#120]
`.pipe(source('app.js'))` on line 30 and `.pipe(gulpif(PRODUCTION, rename('app.min.js')))` on line 37 in file js.js should be replaced with variable from Gulp's config.js.

**Comment by kettanaito** [comment]
There is also a good way to add a suffix instead of duplicating the whole filename.
I remember using this approach, but cannot find the project config where. It looks like this:
```js
method({
    base: config.JS_ENTRY, // app.js
    suffix: '.min' // => app.min.js
});
```
This is just an example. I will post the actual code here if I find it, or maybe you've used it already.

**Comment by vbulant** [comment]
Yep it's used somewhere in the devstack. Gonna do it like that. Thanks fot the suggestion!
