### ISSUE TITLE
Correct environment setup for React, Redux

### ISSUE THREAD

**Issue by vbulant** [actum/gulp-dev-stack#121]
Run the app in production mode: `gulp` and see the console.

```
Warning: It looks like you're using a minified copy of the development build of React. When deploying React apps to production, make sure to use the production build which skips development warnings and is faster. See https://fb.me/react-minification for more details.
```

```
app.min.js:12 You are currently using minified code outside of NODE_ENV === 'production'. This means that you are running a slower development build of Redux. You can use loose-envify (https://github.com/zertosh/loose-envify) for browserify or DefinePlugin for webpack (http://stackoverflow.com/questions/30030031) to ensure you have the correct code for your production build.
```

**Comment by vbulant** [comment]
The 2nd warning might be caused by uppercase env string in config.environment.type. I believe it should be lowercase so when the code is being minified, dev/prod conditions can be met:

```js
if (process.env.NODE_ENV === 'development') { /* development code */ }
```

**Comment by kettanaito** [comment]
@vbulant I think both these errors may be solved by setting `process.env.NODE_ENV` to `development/production` (lowercase) when building the app.

I do not have experience testing this, but in Webpack examples when you build app you set NODE_ENV this way, and React catches `propcess.env.NODE_ENV` and build sources appropriately.

Have you tried setting it to prod?

**Comment by vbulant** [comment]
Yep that’s what I meant by the second comment. As of now, we have uppercase PRODUCTION/DEVELOPMENT values in process.env.NODE_ENV and they should be lowercase as far as I know. Gonna test it as soon as possible. Thanks.

**Comment by vbulant** [comment]
Setting lowercase `development`/`production` worked 👍
