### ISSUE TITLE
Stylelint doesn’t fail after error in production mode

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#130]
`failAfterError: DEVELOPMENT ? true : false,`

**Comment by kettanaito** [comment]
`DEVELOPMENT` is always a boolean:
```js
const isProduction = config.environment.isProduction;

{
    failAfterError: isProduction
}
```

**Comment by kettanaito** [comment]
@janpanschab should correctly rely on environment now: https://github.com/actum/gulp-dev-stack/pull/131.
