### ISSUE TITLE
single vs double colon pseudo elements

### ISSUE THREAD

**Issue by ronaldruzicka** [actum/gulp-dev-stack#135]
I recently found out, that stylelint requires a single colon pseudo-elements (:before, :after, etc.), but it's recommended to use double colon (::before, ::after, etc.). Since we don't have to support IE8, we should use double colon pseudo-elements, to better distinguish from pseudo-clasess.

**Comment by vbulant** [comment]
"It's recommened to use double colon" – could you link the recommendation?

**Comment by ronaldruzicka** [comment]
I can't find an article where they really **recommend** it, but it was created to differentiate the pseudo classes from elements, and since we don't have to support IE8, which is the only browser not supporting `::pseudo-element` syntax, we probably shouldn't force the older syntax by stylelint. And maybe leave it for the developer to decide.
