### ISSUE TITLE
Stylelint config standard update to 16.0.0

### ISSUE THREAD

**Issue by ronaldruzicka** [actum/gulp-dev-stack#147]
I would suggest to update the `stylelint-config-standard` package to the latest version `16.0.0`, because the version we use has some deprecated rules:
![snimek obrazovky 2017-03-03 v 10 17 22](https://cloud.githubusercontent.com/assets/20684387/23545361/5969473a-fffb-11e6-82cd-786ba462f2e6.png)

**Comment by vbulant** [comment]
Agreed, go ahead pls :)
