### ISSUE TITLE
stylelint number-leading-zero null

### ISSUE THREAD

**Issue by ronaldruzicka** [actum/gulp-dev-stack#149]
I just found out, that we are using a null value in number-leading-zero rule for stylelint. Does it mean that we want to use both `.4s` and `0.4s` syntax? Shouldn't we agree on one option to use?

I'm personally using syntax without the leading zero: `.4s`

For example it is recommended on [codestyle.co](http://codestyle.co/Guidelines/css#Syntax)
> Don't prefix property values or color parameters with a leading zero (e.g., .5 instead of 0.5 and -.5px instead of -0.5px)

**Comment by kettanaito** [comment]
Definitely should agree on one approach.
My vote goes for `.4s`.
