### ISSUE TITLE
CSS duplicates caused by less-plugin-glob

### ISSUE THREAD

**Issue by vbulant** [actum/gulp-dev-stack#15]
When using glob imports in LESS and processing them using less-plugin-glob, globbed imports are duplicated in final CSS.

**Comment by vbulant** [comment]
So, when using lessPluginGlob in Grunt stack, everything works just fine. This issue is related to lessPluginGlob in combination with Gulp somehow. I tried all I could think of with no success.

Proposed solution is to replace lessPluginGlob with https://github.com/jsahlen/gulp-css-globbing which is more gulp-ish. Its benefit is that it can be used with any pre/post/processor or even plain CSS so it's more future proof.

I briefly tested it and works just fine (yet) :).

**Comment by janpanschab** [comment]
I have just implement gulp-css-globbing on yachtcharter and works great.  :+1:

**Comment by vbulant** [comment]
Nice, updated.
