### ISSUE TITLE
SVG task fail when creating new svg icon to sprite folder

### ISSUE THREAD

**Issue by ronaldruzicka** [actum/gulp-dev-stack#152]
When you have a `gulp --dev` running and you create a new icon inside a SVG sprite folder, the task will shut down with an error 
![image](https://cloud.githubusercontent.com/assets/20684387/24446319/5b175b04-146d-11e7-8928-b23adb06b30d.png)

But if you create the icon inside svg folder outside the sprite folder, it works normally, nothing breaks.

Does anyone have the same behavior?

**Comment by kettanaito** [comment]
@ronaldruzicka so you are trying to add new icon while devstack is performing initial build?

**Comment by ronaldruzicka** [comment]
@kettanaito when `gulp --dev` is running and you create a new icon directly inside a sprite folder (`gfx/sprite`) you get that error. But I'm not sure how much we can do about it, it's probably mostly for the plugin developers. But you can just create icon inside `gfx` folder and then move it to ,`gfx/sprite` and it works.

**Comment by ronaldruzicka** [comment]
I think we can close this issue, because it's not a bug on our side
