### ISSUE TITLE
remove old gulp task: gulp-uglify

### ISSUE THREAD

**Issue by Lin84** [actum/gulp-dev-stack#167]
in the gulp task for JS we have 2 plugins that do the same thing = Minify JavaScript with UglifyJS2.
'gulp-uglify' 
and 
'uglifyify'

We should use only one of them. As @janpanschab recommended: using only 'uglifyify' and remove 'gulp-uglify'.

**Comment by ronaldruzicka** [comment]
I just tested the missing `uglify` task in Walmark project, and there was a significant difference between the file size.
with: 237KB
without: 731KB

So I think that we should put it back to dev stack.

**Comment by vbulant** [comment]
@ronaldruzicka Yes, we should. A bit of reasoning: https://github.com/actum/gulp-dev-stack/pull/168#issuecomment-300084283
