### ISSUE TITLE
Browserify don’t know about process.env.NODE_ENV

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#20]
React and other libraries need process.env.NODE_ENV for proper minification. Great also for Redux "real world example" workflow.

There are 2 possibilities:
1. use babel - http://babeljs.io/docs/plugins/transform-inline-environment-variables/
2. use envify - using transformation in browserify - https://www.npmjs.com/package/envify

I’m not sure which choose. Babel is maybe more simple to implement?

**Comment by janpanschab** [comment]
On Yachtacharter I just used envify and it saves 55kB - 6% of JS file size.

**Comment by vbulant** [comment]
Are you sure it doesn't work in the latest version? I've implemented and tested that some time ago.
See https://github.com/actum/gulp-dev-stack/blob/master/gulp/tasks/js.js

There is envify + uglifyify for proper browserify env handling and minification as well as uglify for minification of the whole bundle…

**Comment by vbulant** [comment]
Yep, it works fine. Related commit: https://github.com/actum/gulp-dev-stack/commit/e46282c2a04e308a12c56e16f9e4021cab1a588c

**Comment by janpanschab** [comment]
Nice, sorry for that :-)
I did not update our old version on YCH.
