### ISSUE TITLE
Add lint to watchify rebuilds

### ISSUE THREAD

**Issue by vbulant** [actum/gulp-dev-stack#25]
I've found out that eslint isn't called during watchify rebuilds…

**Comment by janpanschab** [comment]
Sometimes

**Comment by vbulant** [comment]
OK, this was just my confusion.

Lint is not connected to watchify. Watchify just bundles js and lint is being called by gulp.watch on changes in watched scripts.

Tested and works. Let's open an issue again if any problem occur.
