### ISSUE TITLE
Clean all task

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#28]
Add task for cleaning all builded, compiled, transpiled files also for `src` folder. Good for testing. Simulate clean git cloned repo.

**Comment by vbulant** [comment]
You mean having one clean task which will clean both `src` and `dist` folders or just adding isDev condition into clean task so that it will clean either `src` or `dist` based on `--dev` param?

**Comment by janpanschab** [comment]
I mean to have sort of `superclean` task. Or reset to defaults. Something like this. One independent task not based on --dev option. But we can discuss it.

**Comment by vbulant** [comment]
Let's talk about it on monday.

**Comment by vbulant** [comment]
`clean` cleans all built stuff in `src` of `dist` folder based on `isDev` param (also will be a part of `prepare` task)
`clean:all` (or similar name) will clean both dev and dist (not part of any build task, just for debugging etc.)
