### ISSUE TITLE
Double lint and less error message

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#3]
Eslint error message logged twice. Once unformatted and once formatted. Displayed should be only formatted.
The same is on less compilation.

**Comment by vbulant** [comment]
Regarding eslint messages – it's caused by eslint.failOnError(). I removed it for --dev so that eslint displays error messages only once.

But we need to keep it for prod so that gulp returns correct exit status. (Without it, gulp always returns 0.)

**Comment by janpanschab** [comment]
Browserify stack is displayed after lint error.

**Comment by vbulant** [comment]
**Current status:** ![eslint_watchify_err](https://cloud.githubusercontent.com/assets/821851/10846974/a55805d8-7f13-11e5-81cb-fcb338f043e2.png)

Eslint reports syntax errors and watchify displays formatted compilation error (as watchify is not dependent on eslint).
This behavior seems fine for me. What do you think?

If we want to go further with this, we could be able to prevent watchify/browserify from compiling scripts containing syntax errors but I have no idea how complex would it be.

**Comment by janpanschab** [comment]
This behavior is not good for me, because if I check the terminal I see only some ugly stack trace log and not the error message.
There are 2 accepted solutions from my point of view.
1) run eslint before watchify runs, but it will slow down the dev process http://stackoverflow.com/questions/30362259/run-eslint-before-watchify-runs
2) format browserify error message and not display the stack trace.

The second one should be more simple and will not affect the speed of reloading the app.

**Comment by janpanschab** [comment]
And now I see the image :smile: This is the second point implemented?

**Comment by vbulant** [comment]
Yep, second it is :+1:
