### ISSUE TITLE
Implement icons ajax loading

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#39]
Because of the bug in IE?? (10 or 11) which fails with displaying svg with use attribute, we are inlining svg sprite right after opening body tag. With https://github.com/Keyamoon/svgxuse we are able to load the big svg sprite asynchronously.

**Comment by janpanschab** [comment]
👍  So coooool (if it works ;-))

**Comment by vbulant** [comment]
Yep, tested briefly in Chrome and IE9 and worked :8ball:
