### ISSUE TITLE
Port 6000 is blocked at Windows (maybe)

### ISSUE THREAD

**Issue by zmrhaljiri** [actum/gulp-dev-stack#40]
Please, change it to some other port, for example 8000.

**Comment by vbulant** [comment]
As far as I know, only ports up to 1024 are reserved.
So this is more likely anything proprietary running on your machine, therefore not an issue to be resolved here.

You are free to change the port locally after cloning the repo…

And btw. http://www.speedguide.net/port.php?port=6000

**Comment by janpanschab** [comment]
Anyway. Use some other fancy cool port to prevent this behavior in the future.

**Comment by vbulant** [comment]
OK, 5001 will do.
