### ISSUE TITLE
Problem with factory function if there is no containers

### ISSUE THREAD

**Issue by janneuman** [actum/gulp-dev-stack#41]
In IE11 I got an error "Object cannot use property or method from" (Array.from) if there is no containers in the DOM. I found some explanation on Stackoverflow: http://stackoverflow.com/a/32000509

Solution can be use if condition:
_if (containers.length) {_
or convert array like object to real array
_return [].slice.apply(containers).map(container => fn(container, ...args));_

**Comment by vbulant** [comment]
Running `npm i babel-polyfill --save` and adding `import 'babel-polyfill';` to the top of your entry js file should work.

You propably have an older version without the polyfill, it is already included in the latest version.

Close the issue if it works please.
