### ISSUE TITLE
CSS linting

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#43]
Implement http://stylelint.io/ as CSS linter. 
Read about it https://css-tricks.com/stylelint/.
Integrate with https://www.npmjs.com/package/gulp-stylelint.
Use or inspire in prepared configs https://www.npmjs.com/browse/keyword/stylelint-config.
Try to find useful plugins (BEM, ...) https://www.npmjs.com/browse/keyword/stylelint-plugin.

**Comment by janpanschab** [comment]
Implemented stylelint with basic config.

**Comment by vbulant** [comment]
I think we shouldn’t mix eslint with stylelint in one file (`gulp/tasks/lint.js`).
If you agree, I’ll separate them like `gulp/tasks/eslint.js`, `gulp/tasks/stylelint.js`.

**Comment by janpanschab** [comment]
Let’s do it.

**Comment by vbulant** [comment]
It’s separated: https://github.com/actum/gulp-dev-stack/commit/cd124c843fda1e01830a1f3d54e48fa3069d011e
