### ISSUE TITLE
Eslint plugins

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#46]
Consider using these eslint plugins:
https://github.com/babel/eslint-plugin-babel
https://github.com/benmosher/eslint-plugin-import
https://github.com/yannickcr/eslint-plugin-react

**Comment by kettanaito** [comment]
If we include eslint-config-airbnb, it comes with these plugins as dependency :)

**Comment by janpanschab** [comment]
Cool, good to know!
