### ISSUE TITLE
Faster gulp start/build

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#48]
As @kettanaito propose, we can significantly speed up gulp start/build. The main problem is babel transpilation.
If we will support node >= 5, we have to rewrite only import/export to require/module.exports and destruction syntax. If we will support node >= 6, destruction is also supported.
For me it’s good trade-off.

/cc @kettanaito @vbulant

**Comment by janpanschab** [comment]
I’ve just push branch `gulpfile-without-babel`. Difference in empty project is:

|  | `gulpfile.babel.js` | `gulpfile.js` |
| --- | --- | --- |
| `gulp build` | 7s | 4s |

**Comment by vbulant** [comment]
+1
