### ISSUE TITLE
Pre-commit hook

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#52]
Add build task to pre-commit hook. http://elijahmanor.com/npm-precommit-scripts/

**Comment by vbulant** [comment]
I find this quite disturbing. Especially during gulp-stack development. What about having it as a pre-push hook/script?

**Rationale:**
- `build` on every commit is pretty time consuming
- I often edit stuff which doesn’t deal with build related files

The push hook would still catch any errors before pushing them to the repo without sacrificing the productivity.

**Comment by janpanschab** [comment]
> `build` on every commit is pretty time consuming

I like it as pre-commit hook, because it prevent broken commits. 

> I often edit stuff which doesn’t deal with build related files

If you are sure you doesn’t deal with build related files you can force a commit with `--no-verify`

**Comment by vbulant** [comment]
I can see your point. Still I’d like to discuss it on the next 1:1 meeting. Closing the issue :)

**Comment by kettanaito** [comment]
How about running only linting tasks on this hook?

**Comment by janpanschab** [comment]
Change to pre-push hook.
