### ISSUE TITLE
Adding gulp-load-plugins

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#53]
How about adding `gulp-load-plugins` to our development stack?

Basically, it will allow to reference any needed (and installed) plugins within each task. I have noticed we used something similar on Grunt-based projects. Is there any drawbacks for gulp?

More information about the plugin is [here](https://www.npmjs.com/package/gulp-load-plugins).

**Comment by janpanschab** [comment]
I like the explicit importing everything what you need. You know exactly which modules you need for this task. It’s a kind of magic.
But I am open to discussion.

**Comment by kettanaito** [comment]
> _it is actually lazy loading the plugins so they are not loaded until you use them._
> **Source:** http://andy-carter.com/blog/automatically-load-gulp-plugins-with-gulp-load-plugins

I think this plugin does not load all the plugins once you include it. It should load them only when you actually call the plugin from its properties:

`import plugins from 'gulp-load-plugins'; // noting is yet loaded`
`...`
`plugins.postCSS(...); // gulp-post-css is being loaded and used`

And you may be able to turn lazy loading off when needed:
`var plugins= require('gulp-load-plugins')({ lazy:false });`

The only drawback I find with this plugin is that it loads only those modules starting by `gulp-` prefix. So, for instance `autoprefixer` will not be loaded in it, and we need to include it manually. But there are still many gulp- modules, so it might be worth it.

**Amendment:** It is possible to specify the pattern to look up by this plugin within its settings:
`var plugins = require("gulp-load-plugins")({ pattern: ['gulp-*', 'gulp.*'] });`
Maybe this eliminates the drawback I find somewhat uncomfortable.

**Comment by janpanschab** [comment]
Lazy loading is not problem for me, it could be feature. My problem is only visual thing. I like explicit imports on top of the file to see what are we using in this module.
If lazy loading is better for performance, let’s try it. But if it’s the same, I would suggest to don’t use it.

**Comment by janpanschab** [comment]
Does anyone try the performance of lazy loading? @kettanaito @vbulant

**Comment by vbulant** [comment]
**Nope**, I’d also like to avoid overengineering and stay transparent with module declarations.

But @kettanaito may try it for sure, maybe we’re missing something.

_Regarding closing and reopening the issue, this was just me accidentaly clicking the close button, sorry for that._

**Comment by kettanaito** [comment]
Thinking more of this issue (and also given it a test), I think it may be unnecessary. Shorthand references are great, but I think it is more important to see clearly what is used on this particular task, and what may be unused.

I like the structure suggested by @janpanschab to divide imported modules more clearly:

``` js
/* Gulp */
const gulp = require('gulp');
// ... gulp-related modules

/* Plugins */
const sass = require('gulp-sass');
// ... task-related modules (uncss, eslint, uglify, etc.)
```

The only thing I would like to clarify is where to put utilities like `gulp-util` or `run-sequence` (and similar). They do not have relation to the task in a direct manner, so probably under Gulp section?

**Comment by janpanschab** [comment]
From my point of view `gulp-util` and `run-sequence` are gulp related.

**Comment by vbulant** [comment]
What is the benefit of this separation?

**Comment by kettanaito** [comment]
@vbulant I think readability only. When there are 10+ modules included in a single task, especially without any oder convention, it takes more time to scan through them. Chaotic order is never good, and alphabetical mixes modules directly related to the task (like `sass` or `uglify`) and modules with no direct connection (rather utilities like `gutil`, `rename`, `path`, etc.)

Separation is important since it allows you to quickly understand what is used in a current task, with a faster ability to change it if required (i.e. updating to a newer technology without leaving any unused chunks out).

Do you think we do not need it?
