### ISSUE TITLE
Moving favicon to gfx

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#54]
I would suggest moving favicon exports to `gfx/favicon` folder, which would make development folder cleaner.

Is there any drawback of doing so?

**Comment by janpanschab** [comment]
It is better to have it in root dir, otherwise we need to add proper redirects.

**Comment by kettanaito** [comment]
@janpanschab Could you please tell me more about those redirects?

**Comment by janpanschab** [comment]
Sorry, I forgot to include [link](http://stackoverflow.com/a/21359390) :-)

**Comment by ronaldruzicka** [comment]
There is also nice explanation here: [realfavicongenerator](http://realfavicongenerator.net/faq#.V9FFfJN95hE)

**Comment by kettanaito** [comment]
Thank you for an explanation, guys. Learn something new every day.
