### ISSUE TITLE
Gulp: Declare the environment only once

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#58]
As I have noticed, we often repeat the same boolean check like this:

``` js
const argv = require('yargs').argv;
...
const isDev = argv.dev || false;
```

What would you say if we move this logic to a separate file, which will determine the type of the environment (dev or prod) once, per any major gulp command start? Basically, it will do the same, and export the boolean result, or even some const flag, which looks more semantic. So then we could use it like this:

``` js
const DEVELOPMENT = require('environment').isDevelopment;
...
if(DEVELOPMENT) { /* do development things */ }
```

**Comment by kettanaito** [comment]
Implemented.
Commit: https://github.com/actum/gulp-dev-stack/commit/71556f38261b049b6331097c7cfb98b038f01364.

If you have any suggestions, please, tell them to me in this topic.

**Comment by janpanschab** [comment]
Just `gulp/tasks/js.js:46-48` use `PRODUCTION` instead of `!DEVELOPMENT`.

**Comment by kettanaito** [comment]
@janpanschab, thank you for pointing that out. It has been changed: https://github.com/actum/gulp-dev-stack/commit/6d5428be060749f38b8af59c7d70894388e36532.

**Comment by kettanaito** [comment]
Regarding the latest changes to the `.gulp/config.js`, I would suggest including environment output to main configuration file, and then use it from the `config.js` everywhere:

``` js
const config = require('./config.js');
const DEVELOPMENT = config.ENVIRONMENT.IS_DEVELOPMENT;
...
if (DEVELOPMENT) { ... }
```
