### ISSUE TITLE
Unify folder names

### ISSUE THREAD

**Issue by vbulant** [actum/gulp-dev-stack#59]
As styles and scripts are now always compiled to dist, we can revert back to a good old folder names: `js` and `css` :)

**Comment by vbulant** [comment]
I think this is a no-go.

After I renamed the folders, the names started to collide (`src/js` vs `dist/js` etc.) because we are setting the `baseDir` (src, dist) in serve task and then link just `css/…` or `js/…`.

I can’t think of any solution to that other than keep using different names in `src` and `dist` folders.

**Comment by janpanschab** [comment]
So once we would like to rename folders we need to be sure compiled files will have unique names - different from files in `src` folder.

**Comment by janpanschab** [comment]
So do we want to rename folders and keep filenames unique or leave it like it’s now? I would prefer leave it to prevent collisions.

**Comment by vbulant** [comment]
I’m fiddling with it right now and it’s getting messy – we’d need to find the right different names for built files and also the gulp task names and config keys wouldn’t match the new folder names (we have 'styles' and 'app' as tasks and configs everywhere).

**So I agree with keeping it as it is now.**
