### ISSUE TITLE
Package.json readability

### ISSUE THREAD

**Issue by vbulant** [actum/gulp-dev-stack#60]
I think I’ve made a stupid mistake of moving eslint, babel etc. configs to package.json.

Now as I’m going through the stack after some time I’m quite lost in the package.json.

I’m willing to move all the configs to separate files (.babelrc, .eslintrc, etc.) if you agree.

**Comment by janpanschab** [comment]
I agree, but not so critical for me.
@kettanaito will be happy :-)
