### ISSUE TITLE
Replace browserify with webpack module bundler

### ISSUE THREAD

**Issue by zoltan-kovac** [actum/gulp-dev-stack#64]
## 1. Use webpack to bundle css, html and javascript files.

Using webpack stream and loaders packages we can move all transformation plugins to one webpack configuration file.
[http://blog.andrewray.me/webpack-when-to-use-and-why/](http://blog.andrewray.me/webpack-when-to-use-and-why/)
## 2. Use webpack for linting and autoprefixing
- Linting and post css plugins can run within webpack pipeline.
## ? Introduce react ready dev stack with Hot module replacement
- requires moving to webpack dev server
- ? adding yeoman to generate different dev stacks ?

**Comment by vbulant** [comment]
Let’s start with 1. – JS bundling and linting.

Then we can decide what to do next.

**Comment by janpanschab** [comment]
But only 1.c. Use webpack to bundle JavaScript. And use Webpack 2 beta version.

Next steps:
1. webpack linting
2. webpack dev server (how to do it with browserSync?)
3. bundle styles with webpack and extract them into separate file

**Comment by kettanaito** [comment]
Webpack is particularly interesting for its [Code Splitting](https://webpack.github.io/docs/code-splitting.html). This is a really useful thing to do in the future.

**Comment by zoltan-kovac** [comment]
Merged with config-new branch
