### ISSUE TITLE
JSON server

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#66]
It would be useful to have a ready-to-use JSON server for imitating requests and responses.

What do you think about it?

**Comment by janpanschab** [comment]
Yes, but only if it starts automatically with `gulp --dev`.

**Comment by vbulant** [comment]
We used something similar for MyMETRO.

My experience:
- we needed custom HTTP status codes (500, 404, …) for ajax responses – that should be doable even with `json-server`
- we used it from time to time for a specific feature only so having it run every time with `gulp --dev` would have been a waste of resources…

**Comment by janpanschab** [comment]
Is it a real problem the waste of resources?

**Comment by vbulant** [comment]
Well I think there are projects without the need for the mock server.

Having the mock server in gulp --dev pipeline would mean that we need to remove the mock server from gulp pipeline if we don’t need it…

Having the mock server in separate folder (eg. `api/index.js`) means either doing nothing or simply removing the folder.

And if needed, we’d simply run eg. `npm run mock`. I think is less invasive.

**Comment by janpanschab** [comment]
OK, so what about to use the power of `yargs` and run it with `gulp --dev --api` (or other option name).

**Comment by janpanschab** [comment]
Documentation is missing!

**Comment by vbulant** [comment]
D'oh!
