### ISSUE TITLE
README.md - Documentation

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#67]
I would like to write an updated version of README.md for our development stack.
## Approximate content
1. Summary
2. Features
3. **Getting started**. Steps required to install and use development stack, from A to Z.
4. **Project structure**. Explain in details what is the structure of the project, what is contained in each folder.
5. **Workflow**. The way to work with the stack. What the works starts from and ends with. How to build a project, etc.
6. **Troubleshooting**. Possible struggles that may rise in a way while installing/working with development stack.
## Would be nice to include
- Gulp tasks (commands) descriptions and usage examples
- Task sequences on different commands to undestand better the chain of transformations that files undergo
- Maintenance. How to update existing projects based on this development stack (talking about outdated Node modules)

**Comment by kettanaito** [comment]
Changes in the Documentation will be handled on the respective [Documentation branch](https://github.com/actum/gulp-dev-stack/tree/documentation).

**Comment by janpanschab** [comment]
@kettanaito I would like to merge this and continue with small improvements of documentation. Would you like to add/change some part? IMHO for now we should only move Extensions part to respective branch. Do you have time for it? If not, I will do it.

**Comment by kettanaito** [comment]
@janpanschab I have pushed some changes to `documentation` branch. You can continue from there. Thank you.

**Comment by vbulant** [comment]
Merged. I’d suggest to close this task and create a new more focused one if needed.
