### ISSUE TITLE
Swig error stops watching swig files

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#7]
https://github.com/colynb/gulp-swig/issues/26
Also try to format error for better reading.

**Comment by vbulant** [comment]
Caused by stopping the task on error anywhere in the pipe.
This will be "fixed" in Gulp 4.x out of the box: https://github.com/gulpjs/gulp/issues/358

We'll introduce temporary workaround using `gulp-plumber`.
