### ISSUE TITLE
Configure hosts on project install

### ISSUE THREAD

**Issue by kettanaito** [actum/gulp-dev-stack#71]
This is rather a minor issue, but maybe you find it useful.

I would like to suggest to add a certain setup process for each new project. For example, when you just cloned the development stack and run `npm install`, guide the developer through a similar process as when creating a new `package.json` (a list of entries awaiting for your input). This way we can allow to set a certain host alias for the project:
```bash
Enter a desired host alias (default: localhost): my-metro.dev
...
Your project is available under "http://my-metro.dev".
```
We may take use of shell commands and this (or similar) packages: [Hostile](https://www.npmjs.com/package/hostile). Script will run the following when any custom input is received:
```bash
hostile set localhost:7000 my-metro.dev
```

What do you think about it?

**Comment by janpanschab** [comment]
I would rather follow the KSS rule. We wan't to have this project easily maintainable. We will not cover all issues, we want to cover the most problematic parts.
What we definitely need to have is better documentation with "install/usage" section, with point for changing project’s `:port` number.

**Comment by kettanaito** [comment]
@janpanschab a good point. Working on the documentation right now. I will cover this aspect.

**Comment by kettanaito** [comment]
This question is no longer discussable, so I will close the issue.
Required information about changing the default port will be added in the documentation.
