### ISSUE TITLE
Omit linting gulpfile

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#73]

**Comment by janpanschab** [comment]
@kettanaito Why we want to do this?

**Comment by kettanaito** [comment]
@janpanschab we moved from Babel in Gulpfile, so Gulp tasks cannot be run through ESLint with the same config as we use on common basis development.

The second reason is that you should not really edit Gulp tasks during the development. Ideally, this is done sometimes by more experienced developers and you just pull the changes if you need. This way there is no need to make gulpfile larger by including this lint.
