### ISSUE TITLE
React

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#87]
Prepare basic React structure, add React dependencies. Question is, if there should be Redux. My opinion is yes.

**Comment by fidelman** [comment]
@janpanschab 
I support the idea about Redux.

**Comment by kettanaito** [comment]
This is what I started doing with extensions. We may configure the letter to install both React standalone and React+Redux (however, I support the idea to ship them together). I think you have already seen the extensions task.

In combination with npm `scripts` we can do something like `npm run install:react+redux` which will trigger a proper Gulp task. The process of installation should be easy 1 command action. What do you think?

**Comment by fidelman** [comment]
what about use webpack for react and its environment? Webpack and Gulp work together perfectly.

**Comment by vbulant** [comment]
@fidelman we are going to use it with React projects.
@zoltan-kovac and @kettanaito prepared `webpack-module-bundler` branch.

For the time being we are sticking with browserify in `master` for non-react projects and `webpack-module-bundler` for React ones.

Maybe we’ll take one step further and use webpack for non-react projects as well, but that’s still undecided. And our webpack integration needs more testing.

**Comment by vbulant** [comment]
@kettanaito If you’re working on your extensions, can you please assign this issue to yourself to avoid that someone else starts working on it?

**Comment by kettanaito** [comment]
@vbulant done. It will take some time, I want to prepare React+Redux and basic component (maybe the very same counter used by Redux examples). It will be in a separate branch.

**Comment by vbulant** [comment]
I see, no rush.

**Comment by kettanaito** [comment]
@janpanschab @vbulant Please, while I am a little busy with the project, may you help in deciding what will we use as an example for React extension?

I can suggest:
* the same example used for Redux - TODO list. So it will be some List component, which will interact with the store.
* simple click counter on <Button />

Also, I would like to hear any technical moments of React example (folder structure, naming conventions, etc.). Thank you.

**Comment by janpanschab** [comment]
@kettanaito I can takeover this task. I have some ideas and hopefully I will have time for it. If you are OK with it, assign it to me.

**Comment by vbulant** [comment]
Regarding example I suggest using one of the official ones from React or Redux websites so that we don’t need to reinvent anything and refer to the documentation/tutorial if needed.

**Comment by kettanaito** [comment]
@janpanschab I am completely fine with that. You've seen an example how I tried to achieve that, so maybe that will be helpful :) Assigning it to you.

**Comment by kettanaito** [comment]
Developing in React with Hot module reloading from Webpack is superb. This is a bold plus to use Webpack :)

**Comment by vbulant** [comment]
Agreed. I’m curious which HMR library/approach did you use. Will check it out soon :)

**Comment by vbulant** [comment]
Btw. it is possible to make it work with browserify as well, but that’s no longer relevant to us I guess.

**Comment by kettanaito** [comment]
@vbulant it is completely possible to use it as middleware in BrowserSync. This is the approach we use on Conrad, since it is not pure React project. I may help in setup of HMR+BrowserSync or HMR standalone as well.

Actually, I must be considered to migrate to webpack completely, but this is another discussion.

**Comment by janpanschab** [comment]
closed by #111
