### ISSUE TITLE
Environment check

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#88]
We need to check minimal version of npm and node. It doesn’t run on npm < 3 and node < 5.

**Comment by vbulant** [comment]
Isn't it enough to list the requrements in readme?

**Comment by janpanschab** [comment]
No, ask Linh and Jan Chalupa :-) Same questions yesterday: why it is not working!?!?!?

**Comment by vbulant** [comment]
I see :) Can we discuss it in person on monday? (I’m in the office on Mon–Wed due to the public holiday.)

**Comment by vbulant** [comment]
Couldn’t get "engines" field in package.json to work. It doesn’t show any warning when versions don’t match.
