### ISSUE TITLE
The optimisation styles recompiling

### ISSUE THREAD

**Issue by fidelman** [actum/gulp-dev-stack#89]
Hello everyone.
Now I would like to discuss optimising gulp file flow, in this case _style_ task.

**Theory and assumption**

I've noticed in _style_ gulp task all files _(/components/*)_ are imported to the 2-3 files. It says the whole content recompiles again if we rebuild it (watch dev mode) and it does not matter, we change 1 row or the whole file.

**Practise and decision**
I suggest to use gulp file flow cache to optimise the one. For example I use [gulp-cached](https://www.npmjs.com/package/gulp-cached) and [gulp-remember](https://www.npmjs.com/package/gulp-remember). There are a lot of plugins to work with the optimisation. 
But be careful with gulp.v4 [_since_ option](https://www.npmjs.com/package/gulp-4.0.build#incremental-builds). This option check only date modification. There some ways when we need to check content. (You delete file, then run gulp. After you reestablish the file via _Ctrl+Z_. Your IDE don't change date modification and gulp will not see this file.)

**Experiment and results**
I've created 10 scss files. After I run gulp in dev mode and see this:
![screen shot 2016-11-14 at 16 39 19 1](https://cloud.githubusercontent.com/assets/15198653/20271713/f5878b6a-aa8b-11e6-8b62-455e3d00210e.png)
Then change 1 option in the one file and see:
![screen shot 2016-11-14 at 16 39 29](https://cloud.githubusercontent.com/assets/15198653/20271740/0a02df86-aa8c-11e6-936e-d9912c939114.png)

After I set above written gulp plugins.
First Run:
![screen shot 2016-11-14 at 16 36 03](https://cloud.githubusercontent.com/assets/15198653/20271789/3076a0b2-aa8c-11e6-9e46-a6fa91727c29.png)
The results are equal +-10%.
Rebuild:
![screen shot 2016-11-14 at 16 36 28](https://cloud.githubusercontent.com/assets/15198653/20271824/5561d586-aa8c-11e6-8fc3-b069b1b112a7.png)
You see. The experiment with 10 files, but if we have 40-100 files.

Thank for your attention. What do you think about it? Do you have exp working with it?

**Comment by vbulant** [comment]
[gulp-cached](https://www.npmjs.com/package/gulp-cached) looks good – it seems it won’t add much complexity to the pipeline.

I’d suggest proceeding with test implementation and doing more thorough test (not just one pass). If the results are significant, let’s adopt it.

_What do others think?_

**Comment by janpanschab** [comment]
Looks good. Let’s test it on much bigger code base. E.g. Conrad in a future.
@fidelman Could you [prepare the task in branch](https://github.com/actum/gulp-dev-stack/blob/master/CONTRIBUTING.md) and once we test it we will create a pull request.

**Comment by fidelman** [comment]
Hello guys!
I have some results, but also I need your opinion about it.

So, I tested the cache keeping in the Conrad project, which has about 30 style modules. 
First, I added the cache plugin to the stylelint task:

    return gulp.src(src.styles.all)
        .pipe(cached('stylelint'))     //
        .pipe(debug())                 //
        .pipe(stylelint({
            failAfterError: false,
            reporters: [{
                formatter: 'string',
                console: true
            }]
        }));

When we change one file **without** the cache, we have:
![screen shot 2016-11-28 at 11 14 59](https://cloud.githubusercontent.com/assets/15198653/20664965/e5c350ec-b55d-11e6-91e8-037c2ca3d4fe.png)
**With** the cache:
![screen shot 2016-11-28 at 11 14 41](https://cloud.githubusercontent.com/assets/15198653/20664973/eefc86e2-b55d-11e6-87a9-1efd2aff5745.png)
Everything is cool!

Working with the style task I faced one big problem.
The structure of the task looks like:
![screen shot 2016-11-28 at 12 42 38](https://cloud.githubusercontent.com/assets/15198653/20667169/3040b8c6-b568-11e6-8be6-8ab8a1fe7daf.png)


We cannot use sass '@import' in the main.scss to put cache to the best way, because sass plugin create one big file, but for the cache we need to keep every file separately. So we need to add every file to the main flow.

So the paradox is creating here. If we keep every file separately, the sass plugin can't translate scss files, because it doesn't see variables (we don't import them to the every file).
I see an opportunity to put the constant files (look at the picture) to the config file and import them to the every file.
This is not the best way to solve this problem, because it is wrong to change config file every times when we have new project or new variables file or directory. Also it is difficult to keep the file order using this pattern.

What do you think about it? Thanks for attention.

**Comment by janpanschab** [comment]
@fidelman Could you push your solution?

**Comment by fidelman** [comment]
I've pushed to the "89-the-optimisation-styles-recompiling" branch

**Comment by janpanschab** [comment]
My recommendation is to use the cache solution only where it’s possible. When it cause a problem, don't use it. 
So, use it in stylelint task, great! 👍 
It is a big problem in scss compilation? Don’t use it.

**Comment by fidelman** [comment]
@janpanschab , OK, thanks!
