### ISSUE TITLE
CSS globbing package is deprecated

### ISSUE THREAD

**Issue by janpanschab** [actum/gulp-dev-stack#90]
We need to replace https://github.com/jsahlen/gulp-css-globbing package. It is no longer maintained.

**Comment by fidelman** [comment]
I've found [https://www.npmjs.com/package/gulp-concat-css](gulp-concat-css), which works **only with CSS**.
Also here are plugins **only for SASS**:
- [https://www.npmjs.com/package/gulp-sass-globbing](url)

- [https://github.com/bleuarg/gulp-sass-glob-import/blob/master/README.md](gulp-sass-glob-import)

- [https://github.com/mathisonian/gulp-sass-bulk-import](gulp-sass-bulk-import)

- [https://github.com/tomgrooffer/gulp-sass-glob](gulp-sass-glob)

**Comment by fidelman** [comment]
I've found [gulp-concat-css](https://www.npmjs.com/package/gulp-concat-css), which works **only with CSS**.
Also here are plugins **only for SASS**:
- [gulp-sass-globbing](https://www.npmjs.com/package/gulp-sass-globbing)
- [gulp-sass-glob-import](https://github.com/bleuarg/gulp-sass-glob-import/blob/master/README.md)
- [gulp-sass-bulk-import](https://github.com/mathisonian/gulp-sass-bulk-import)
- [gulp-sass-glob](https://github.com/tomgrooffer/gulp-sass-glob)
